### ISSUE TITLE
Is this code dead?

### ISSUE THREAD

**Issue by zieglerjm** [angular-microfrontends/navbar#10]
It will not compile for me.

c:\...> npm run build

> @angular-microfrontends/navbar@0.0.0 build
> ng build

Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling single-spa-angular/internals : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling single-spa-angular : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
10% building 1/2 modules 1 active ...Health\UI\navbar\node_modules\systemjs-webpack-interop\resource-query-public-path.js?systemjsModuleName=%40angular-microfrontends%2Fnavbar&rootDirectoryLevel=1node:internal/crypto/hash:79
  this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
....
{
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.14.0

**Comment by joeldenning** [comment]
I haven't worked on this project for awhile and don't know if it still boots up. I'm open to reviving it, but it's not high priority. If you're open to funding the work, I can prioritize it.
